name: directus_api_manager
description: Communicate with a Directus server using its REST API.
version: 1.14.3
repository: https://github.com/maxbritto/directus_api_manager

environment:
     sdk: ^3.5.3

dependencies:
     http: ">=0.13.4 <2.0.0"
     http_parser: ^4.0.2
     reflectable: ">=4.0.1 <6.0.0"
     web_socket_channel: ^3.0.3
     extension_dart_tools: ^1.4.1
     meta: "^1.15.0"
     mutex: ^3.1.0

dev_dependencies:
     reflectable_builder: any
     build_runner: any
     lints: ^6.0.0
     test: ^1.26.3
